export const regionToCountryCode: Record<string, string> = {
  'United States': 'US',
  'United Kingdom': 'GB',
  Germany: 'DE',
  France: 'FR',
  Canada: 'CA',
  Australia: 'AU',
  Japan: 'JP',
  China: 'CN',
  India: 'IN',
  Singapore: 'SG',
  'Hong Kong': 'HK',
  'South Korea': 'KR',
  Frankfurt: 'DE', // Frankfurt is in Germany
  Brazil: 'BR',
  Mexico: 'MX',
  Russia: 'RU',
  'South Africa': 'ZA',
  Turkey: 'TR',
  Italy: 'IT',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Netherlands: 'NL',
  Belgium: 'BE',
  Norway: 'NO',
  Finland: 'FI',
  Denmark: 'DK',
  Poland: 'PL',
  Austria: 'AT',
  Ireland: 'IE',
  'Czech Republic': 'CZ',
  Greece: 'GR',
  Portugal: 'PT',
  Israel: 'IL',
  'United Arab Emirates': 'AE',
  'Saudi Arabia': 'SA',
  Kuwait: 'KW',
  Qatar: 'QA',
  Oman: 'OM',
  Bahrain: 'BH',
  Indonesia: 'ID',
  Malaysia: 'MY',
  Thailand: 'TH',
  Philippines: 'PH',
  Vietnam: 'VN',
  Pakistan: 'PK',
  'Sri Lanka': 'LK',
  Bangladesh: 'BD',
  Chile: 'CL',
  Argentina: 'AR',
  Colombia: 'CO',
  Peru: 'PE',
  'New Zealand': 'NZ',
  Taiwan: 'TW',
  Egypt: 'EG',
  Nigeria: 'NG',
  Kenya: 'KE',
  Romania: 'RO',
  Hungary: 'HU',
  Bulgaria: 'BG',
  Ukraine: 'UA',
  Slovakia: 'SK',
  Croatia: 'HR',
  Serbia: 'RS',
  Slovenia: 'SI',
  Latvia: 'LV',
  Lithuania: 'LT',
  Estonia: 'EE',
  Belarus: 'BY',
  Kazakhstan: 'KZ',
  Uzbekistan: 'UZ',
  Turkmenistan: 'TM',
  Azerbaijan: 'AZ',
  Moldova: 'MD',
  Georgia: 'GE',
  Armenia: 'AM',
  Albania: 'AL',
  Kosovo: 'XK',
  Montenegro: 'ME',
  'North Macedonia': 'MK',
  'Bosnia and Herzegovina': 'BA',
  Andorra: 'AD',
  Liechtenstein: 'LI',
  'San Marino': 'SM',
  Monaco: 'MC',
  'Vatican City': 'VA',
  Luxembourg: 'LU',
  Malta: 'MT',
  Cyprus: 'CY',
  Gibraltar: 'GI',
  Bermuda: 'BM',
  'Cayman Islands': 'KY',
  'British Virgin Islands': 'VG',
  Barbados: 'BB',
  Bahamas: 'BS',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  Grenada: 'GD',
  'Trinidad and Tobago': 'TT',
  Jamaica: 'JM',
  Haiti: 'HT',
  'Dominican Republic': 'DO',
  Cuba: 'CU',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Nicaragua: 'NI',
  'El Salvador': 'SV',
  Guatemala: 'GT',
  Honduras: 'HN',
  Belize: 'BZ',
  'Saint Barthelemy': 'BL',
  'Sint Maarten': 'SX',
  'Saint Pierre and Miquelon': 'PM',
  Montserrat: 'MS',
  Anguilla: 'AI',
  Aruba: 'AW',
  Bonaire: 'BQ',
  Curacao: 'CW',
  'Sint Eustatius': 'NL',
  Saba: 'NL',
  'Saint Martin': 'FR',
  Guadeloupe: 'GP',
  Martinique: 'MQ',
  'French Guiana': 'GF',
  'Saint Helena': 'SH',
  'Ascension Island': 'AC',
  'Falkland Islands': 'FK',
  'South Georgia': 'GS',
  'Pitcairn Islands': 'PN',
  'American Samoa': 'AS',
  'United States Virgin Islands': 'VI',
  Guam: 'GU',
  'Northern Mariana Islands': 'MP',
  'Marshall Islands': 'MH',
  Palau: 'PW',
  Micronesia: 'FM',
  Nauru: 'NR',
  Tuvalu: 'TV',
  Kiribati: 'KI',
  Vanuatu: 'VU',
  'Solomon Islands': 'SB',
  Tonga: 'TO',
  Samoa: 'WS',
  Fiji: 'FJ',
  'New Caledonia': 'NC',
  'Wallis and Futuna': 'WF',
  'French Polynesia': 'PF',
  'Cook Islands': 'CK',
  Niue: 'NU',
  Tokelau: 'TK',
  Pitcairn: 'PN',
  'Easter Island': 'CL',
};
